name: Deploy to GitHub Pages

on:
  push:
    branches: ['main']

# Pages 배포에 필요한 권한을 워크플로우 레벨에 명시(권장)
permissions:
  contents: read
  pages: write
  id-token: write

# 동시 배포 충돌 방지(권장)
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build_site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        env:
          BASE_PATH: '/${{ github.event.repository.name }}'
        run: npm run build

      - name: Upload Pages artifact
        # v3는 내부적으로 upload-artifact@v4를 사용 → 에러 해결
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/

  deploy:
    needs: build_site
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
